import type {IcrcRequestedScopes} from '../types/icrc-requests';
import {IcrcScopedMethodSchema} from '../types/icrc-standards';

export const RELYING_PARTY_CHECK_WALLET_STATUS_INTERVAL = 5000;

const RELYING_PARTY_TIMEOUT_IN_MILLISECONDS_WITH_USER_INTERACTION = 60 * 2 * 1000;
const RELYING_PARTY_TIMEOUT_IN_MILLISECONDS_WITHOUT_USER_INTERACTION = 5000;

export const RELYING_PARTY_CONNECT_TIMEOUT_IN_MILLISECONDS =
  RELYING_PARTY_TIMEOUT_IN_MILLISECONDS_WITH_USER_INTERACTION;
export const RELYING_PARTY_TIMEOUT_REQUEST_SUPPORTED_STANDARD =
  RELYING_PARTY_TIMEOUT_IN_MILLISECONDS_WITHOUT_USER_INTERACTION;
export const RELYING_PARTY_TIMEOUT_REQUEST_PERMISSIONS =
  RELYING_PARTY_TIMEOUT_IN_MILLISECONDS_WITH_USER_INTERACTION;
export const RELYING_PARTY_TIMEOUT_PERMISSIONS =
  RELYING_PARTY_TIMEOUT_IN_MILLISECONDS_WITHOUT_USER_INTERACTION;
export const RELYING_PARTY_TIMEOUT_ACCOUNTS =
  RELYING_PARTY_TIMEOUT_IN_MILLISECONDS_WITH_USER_INTERACTION;
export const RELYING_PARTY_TIMEOUT_CALL_CANISTER =
  RELYING_PARTY_TIMEOUT_IN_MILLISECONDS_WITH_USER_INTERACTION;
export const RELYING_PARTY_TIMEOUT_REQUEST_STATUS =
  RELYING_PARTY_TIMEOUT_IN_MILLISECONDS_WITHOUT_USER_INTERACTION;

export const RELYING_PARTY_DEFAULT_SCOPES: IcrcRequestedScopes = {
  scopes: Object.values(IcrcScopedMethodSchema.enum).map((method) => ({method}))
};
