// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';

export type MetadataValue =
	| { Int: bigint }
	| { Nat: bigint }
	| { Blob: Uint8Array | number[] }
	| { Text: string };
export interface _SERVICE {
	build_version: ActorMethod<[], string>;
	icrc1_metadata: ActorMethod<[], Array<[string, MetadataValue]>>;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
