#!/usr/bin/env bash

# Compiles candid .did files to .idl.js and .d.ts

set -euo pipefail

did_files_to_compile() {
  local path=src/declarations

  find ${path} -type f -name '*.did' |
    grep -vE ${path}/+payloads.did
}

# Normal API access.
compile_did() {
  local didfile="$1"
  local didfolder="$(dirname "$didfile")"
  local jsFactoryFile="$(echo "$didfile" | sed 's/did$/idl.js/g')"
  local tsFactoryFile="$(echo "$didfile" | sed 's/did$/idl.d.ts/g')"

  generate_did "$didfile" "$didfolder" "$jsFactoryFile" "$tsFactoryFile"
}

generate_did() {
  local didfile="$1"
  local didfolder="$2"
  local jsFactoryFile="$3"
  local tsFactoryFile="$4"

  local tsfile="$(echo "$didfile" | sed 's/did$/d.ts/g')"

  # icp-bindgen non-optional output folder and filenames
  local declarationsfolder="${didfolder}/declarations"
  local filename="$(basename "$didfile" .did)"
  local generatedTsfile="${declarationsfolder}/${filename}.did.d.ts"
  local generatedJsfile="${declarationsfolder}/${filename}.did.js"

  # --actor-disabled: skip generating actor files, since we handle those ourselves
  # --force: overwrite files. Required; otherwise, icp-bindgen would delete files at preprocess,
  # which causes issues when multiple .did files are located in the same folder.
  # --declarations-root-exports: expose generated declarations at the root of the modules.
  # Useful when the consumer encode or decode Candid messages themselves.
  npx icp-bindgen --did-file "${didfile}" --out-dir "${didfolder}" --actor-disabled --force --declarations-root-exports

  # icp-bindgen generates the files in a `declarations` subfolder
  # using suffixes different from those historically used in ic-js.
  # That's why we have to post-process the results.
  mv "${generatedTsfile}" "${tsfile}"
  mv "${generatedJsfile}" "${jsFactoryFile}"
  rm -r "${declarationsfolder}"

  generate_did_factory_ts "${tsFactoryFile}"
}

generate_did_factory_ts() {
  local tsFactoryFile="$1"

  echo "import type { IDL } from \"@icp-sdk/core/candid\";export const idlFactory: IDL.InterfaceFactory;" >"${tsFactoryFile}"
}

did_files_to_compile | while read line; do
  compile_did "$line"
done

# didc might generate definition file with invalid trailing comma which can be fixed by the code formatter
# in addition, types we create with generate_did_factory_ts are not formatted
npm run format
