#!/bin/bash

DIR=src/declarations

if [ ! -d "$DIR" ]; then
  mkdir "$DIR"
fi

curl -sSL https://raw.githubusercontent.com/dfinity/wg-identity-authentication/main/topics/ICRC-21/ICRC-21.did -o "$DIR"/icrc-21.did
curl -sSL https://raw.githubusercontent.com/dfinity/ICRC-1/refs/heads/main/standards/ICRC-1/ICRC-1.did -o "$DIR"/icrc-1.did
curl -sSL https://raw.githubusercontent.com/dfinity/ICRC-1/refs/heads/main/standards/ICRC-2/ICRC-2.did -o "$DIR"/icrc-2.did