name: Prepare

description: Checkout and install dependencies

inputs:
  folder:
    description: 'The folder in which to run npm ci'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      shell: bash
      run: npm ci --force
      working-directory: ${{ inputs.folder }}
