name: Devops Checks

on:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  lint-github-actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Lint GitHub Actions with zizmor
        run: pipx run zizmor==1.22.0 .github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  devops-checks-pass:
    needs: ['lint-github-actions']
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Cleared for merging
        run: echo OK
