name: Lib Tests

on:
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Tests
        run: npm run test

  lib-tests-pass:
    name: lib-tests-pass
    needs: ['tests']
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Cleared for merging
        run: echo OK
